---
- name: Install Docker and run Nginx container
  hosts: all
  become: true
  vars:
    container_name: nginx
  tasks:
  - name: Get Ubuntu codename
    command: lsb_release -c
    register: ubuntu_codename
  - name: Print Ubuntu codename
    debug:
      msg: "{{ ubuntu_codename.stdout_lines[0].split()[1] | trim }}"  
  - name: Update package manager
    package:
      name: python3-apt
      state: latest
  - name: Install prerequirements
    ansible.builtin.apt:
      update_cache: yes
      name: apt-transport-https, ca-certificates, curl, software-properties-common 
      state: present
  - name: Add the key of Docker oficial repository 
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present        
  - name: Add specified Docker repository into sources list
    ansible.builtin.apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu {{ ubuntu_codename.stdout_lines[0].split()[1] | trim }} stable
      state: present
  - name: Install Docker
    apt:
      name: docker-ce, docker-ce-cli, containerd.io, docker-compose-plugin
      state: latest
  - name: Start Docker service
    service:
      name: docker
      state: started
  - name: Add user ubuntu to the group docker
    user:
      name: ubuntu
      groups: docker
      append: true    
  #- name: Run Nginx container
  #  command: docker run --name "{{ container_name }}" -d -p 80:80 nginx
  
  - name: Install kubectl using curl
    shell: curl -LO https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
  - name: Make kubectl executable
    command: chmod +x kubectl
  - name: Move kubectl to /usr/local/bin
    command: sudo mv kubectl /usr/local/bin/
  - name: Check kubectl version
    shell: kubectl version --output=yaml
    register: kubectl_version
  #- name: Debug output
  #  debug:
  #    var: kubectl_version.stdout_lines
